#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

blockMesh > log.blockMesh
checkMesh > log.checkMeshA
wedgePlease -angle 5 > log.wedgePlease
checkMesh > log.checkMeshB
collapseEdges -overwrite > log.collapseEdges
checkMesh > log.checkMeshC
changeDictionary -instance constant/polyMesh -dict system/changeDictionaryDict.toWedge
runApplication createPatch -overwrite # removing patch axis
