#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

blockMesh
wedgePlease -angle 5
# checkMesh > log.checkMeshB # bad
collapseEdges -overwrite
# checkMesh > log.checkMeshC # good
foamDictionary constant/polyMesh/boundary -entry entry0.wedge_pos.type -set wedge
foamDictionary constant/polyMesh/boundary -entry entry0.wedge_neg.type -set wedge
createPatch -overwrite #  removing patch axis
