#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

blockMesh > log.blockMesh
checkMesh > log.checkMeshA
wedgePlease -angle 5 > log.wedgePlease
checkMesh > log.checkMeshB
collapseEdges -overwrite > log.collapseEdges
checkMesh > log.checkMeshC
foamDictionary constant/polyMesh/boundary -entry entry0.wedge_pos.type -set wedge
foamDictionary constant/polyMesh/boundary -entry entry0.wedge_neg.type -set wedge
createPatch -overwrite > log.createPatch  # removing patch axis
checkMesh > log.checkMeshD
