#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

fluentMeshToFoam -scale 1e-3 fim_01_00_msh_C_01_01.fluentMesh > log.fluentMeshToFoam
wedgePlease -angle 5
# checkMesh > log.checkMesh_bad
collapseEdges -overwrite # remove the 0 length edges on the axis patch
# checkMesh > log.checkMesh_good
# type wedge boundary condition
foamDictionary constant/polyMesh/boundary -entry entry0.wedge_pos.type -set wedge
foamDictionary constant/polyMesh/boundary -entry entry0.wedge_neg.type -set wedge
createPatch -overwrite # removing patch axis which contains no faces
